version: '3'
services:
  smartfile-chat-app:
    image: smartfile-chat-app:latest
    build: ./app
    command:  uvicorn main:app --host 0.0.0.0 --port 8080
    volumes:
    - ./:/app
    ports:
    - 8080:8080